package Plync::WBXML::Schema::ActiveSync;

use strict;
use warnings;

use base 'Plync::WBXML::Schema::Base';

our $NAMESPACES = {
    'AirSync'           => 0x00,
    'Contacts'          => 0x01,
    'Email'             => 0x02,
    'Calendar'          => 0x04,
    'Move'              => 0x05,
    'ItemEstimate'      => 0x06,
    'FolderHierarchy'   => 0x07,
    'MeetingResponse'   => 0x09,
    'ResolveRecipients' => 0x0a,
    'ValidateCert'      => 0x0b,
    'Contacts2'         => 0x0c,
    'Ping'              => 0x0d,
    'Provision'         => 0x0e,
    'Search'            => 0x0f,
    'GAL'               => 0x10,
    'AirSyncBase'       => 0x11,
    'Settings'          => 0x12,
    'DocumentLibrary'   => 0x13,
    'ItemOperations'    => 0x14,
    'ComposeMail'       => 0x15,
    'Email2'            => 0x16,
    'Notes'             => 0x17,
    'RightsManagement'  => 0x18,
};

our $PAGES = {
    0x00 => 'AirSync',
    0x01 => 'Contacts',
    0x02 => 'Email',
    0x04 => 'Calendar',
    0x05 => 'Move',
    0x06 => 'ItemEstimate',
    0x07 => 'FolderHierarchy',
    0x09 => 'MeetingResponse',
    0x0a => 'ResolveRecipients',
    0x0b => 'ValidateCert',
    0x0c => 'Contacts2',
    0x0d => 'Ping',
    0x0e => 'Provision',
    0x0f => 'Search',
    0x10 => 'GAL',
    0x11 => 'AirSyncBase',
    0x12 => 'Settings',
    0x13 => 'DocumentLibrary',
    0x14 => 'ItemOperations',
    0x15 => 'ComposeMail',
    0x16 => 'Email2',
    0x17 => 'Notes',
    0x18 => 'RightsManagement',
};

our $CODES = {

    # AirSync
    0x00 => {
        0x05 => 'Sync',
        0x06 => 'Responses',
        0x07 => 'Add',
        0x08 => 'Change',
        0x09 => 'Delete',
        0x0A => 'Fetch',
        0x0B => 'SyncKey',
        0x0C => 'ClientId',
        0x0D => 'ServerId',
        0x0E => 'Status',
        0x0F => 'Collection',
        0x10 => 'Class',
        0x12 => 'CollectionId',
        0x13 => 'GetChanges',
        0x14 => 'MoreAvailable',
        0x15 => 'WindowSize',
        0x16 => 'Commands',
        0x17 => 'Options',
        0x18 => 'FilterType',
        0x1B => 'Conflict',
        0x1C => 'Collections',
        0x1D => 'ApplicationData',
        0x1E => 'DeletesAsMoves',
        0x20 => 'Supported',
        0x21 => 'SoftDelete',
        0x22 => 'MIMESupport',
        0x23 => 'MIMETruncation',
        0x24 => 'Wait',
        0x25 => 'Limit',
        0x26 => 'Partial',
        0x27 => 'ConversationMode',
        0x28 => 'MaxItems',
        0x29 => 'HeartbeatInterval',
    },

    # Contacts
    0x01 => {
        0x05 => 'Anniversary',
        0x06 => 'AssistantName',
        0x07 => 'AssistantTelephoneNumber',
        0x08 => 'Birthday',
        0x0C => 'Business2PhoneNumber',
        0x0D => 'BusinessCity',
        0x0E => 'BusinessCountry',
        0x0F => 'BusinessPostalCode',
        0x10 => 'BusinessState',
        0x11 => 'BusinessStreet',
        0x12 => 'BusinessFaxNumber',
        0x13 => 'BusinessPhoneNumber',
        0x14 => 'CarPhoneNumber',
        0x15 => 'Categories',
        0x16 => 'Category',
        0x17 => 'Children',
        0x18 => 'Child',
        0x19 => 'CompanyName',
        0x1A => 'Department',
        0x1B => 'Email1Address',
        0x1C => 'Email2Address',
        0x1D => 'Email3Address',
        0x1E => 'FileAs',
        0x1F => 'FirstName',
        0x20 => 'Home2PhoneNumber',
        0x21 => 'HomeCity',
        0x22 => 'HomeCountry',
        0x23 => 'HomePostalCode',
        0x24 => 'HomeState',
        0x25 => 'HomeStreet',
        0x26 => 'HomeFaxNumber',
        0x27 => 'HomePhoneNumber',
        0x28 => 'JobTitle',
        0x29 => 'LastName',
        0x2A => 'MiddleName',
        0x2B => 'MobilePhoneNumber',
        0x2C => 'OfficeLocation',
        0x2D => 'OtherCity',
        0x2E => 'OtherCountry',
        0x2F => 'OtherPostalCode',
        0x30 => 'OtherState',
        0x31 => 'OtherStreet',
        0x32 => 'PagerNumber',
        0x33 => 'RadioPhoneNumber',
        0x34 => 'Spouse',
        0x35 => 'Suffix',
        0x36 => 'Title',
        0x37 => 'Webpage',
        0x38 => 'YomiCompanyName',
        0x39 => 'YomiFirstName',
        0x3A => 'YomiLastName',
        0x3C => 'Picture',
        0x3D => 'Alias',
        0x3E => 'WeightedRank',
    },

    # Email
    0x02 => {
        0x0F => 'DateReceived',
        0x11 => 'DisplayTo',
        0x12 => 'Importance',
        0x13 => 'MessageClass',
        0x14 => 'Subject',
        0x15 => 'Read',
        0x16 => 'To',
        0x17 => 'CC',
        0x18 => 'From',
        0x19 => 'ReplyTo',
        0x1A => 'AllDayEvent',
        0x1B => 'Categories',
        0x1C => 'Category',
        0x1D => 'DTStamp',
        0x1E => 'EndTime',
        0x1F => 'InstanceType',
        0x20 => 'BusyStatus',
        0x21 => 'Location',
        0x22 => 'MeetingRequest',
        0x23 => 'Organizer',
        0x24 => 'RecurrenceId',
        0x25 => 'Reminder',
        0x26 => 'ResponseRequested',
        0x27 => 'Recurrences',
        0x28 => 'Recurrence',
        0x29 => 'Recurrence_Type',
        0x2A => 'Recurrence_Until',
        0x2B => 'Recurrence_Occurrences',
        0x2C => 'Recurrence_Interval',
        0x2D => 'Recurrence_DayOfWeek',
        0x2E => 'Recurrence_DayOfMonth',
        0x2F => 'Recurrence_WeekOfMonth',
        0x30 => 'Recurrence_MonthOfYear',
        0x31 => 'StartTime',
        0x32 => 'Sensitivity',
        0x33 => 'TimeZone',
        0x34 => 'GlobalObjId',
        0x35 => 'ThreadTopic',
        0x39 => 'InternetCPID',
        0x3A => 'Flag',
        0x3B => 'FlagStatus',
        0x3C => 'ContentClass',
        0x3D => 'FlagType',
        0x3E => 'CompleteTime',
        0x3F => 'DisallowNewTimeProposal',
    },

    # Calendar
    0x04 => {
        0x05 => 'TimeZone',
        0x06 => 'AllDayEvent',
        0x07 => 'Attendees',
        0x08 => 'Attendee',
        0x09 => 'Attendee_Email',
        0x0A => 'Attendee_Name',
        0x0D => 'BusyStatus',
        0x0E => 'Categories',
        0x0F => 'Category',
        0x11 => 'DTStamp',
        0x12 => 'EndTime',
        0x13 => 'Exception',
        0x14 => 'Exceptions',
        0x15 => 'Exception_Deleted',
        0x16 => 'Exception_StartTime',
        0x17 => 'Location',
        0x18 => 'MeetingStatus',
        0x19 => 'Organizer_Email',
        0x1A => 'Organizer_Name',
        0x1B => 'Recurrence',
        0x1C => 'Recurrence_Type',
        0x1D => 'Recurrence_Until',
        0x1E => 'Recurrence_Occurrences',
        0x1F => 'Recurrence_Interval',
        0x20 => 'Recurrence_DayOfWeek',
        0x21 => 'Recurrence_DayOfMonth',
        0x22 => 'Recurrence_WeekOfMonth',
        0x23 => 'Recurrence_MonthOfYear',
        0x24 => 'Reminder',
        0x25 => 'Sensitivity',
        0x26 => 'Subject',
        0x27 => 'StartTime',
        0x28 => 'UID',
        0x29 => 'Attendee_Status',
        0x2A => 'Attendee_Type',
        0x33 => 'DisallowNewTimeProposal',
        0x34 => 'ResponseRequested',
        0x35 => 'AppointmentReplyTime',
        0x36 => 'ResponseType',
        0x37 => 'CalendarType',
        0x38 => 'IsLeapMonth',
        0x39 => 'FirstDayOfWeek',
        0x3A => 'OnlineMeetingConfLink',
        0x3B => 'OnlineMeetingExternalLink',
    },

    # Move
    0x05 => {
        0x05 => 'MoveItems',
        0x06 => 'Move',
        0x07 => 'SrcMsgId',
        0x08 => 'SrcFldId',
        0x09 => 'DstFldId',
        0x0A => 'Response',
        0x0B => 'Status',
        0x0C => 'DstMsgId',
    },

    # ItemEstimate
    0x06 => {
        0x05 => 'GetItemEstimate',
        0x06 => 'Version',
        0x07 => 'Collections',
        0x08 => 'Collection',
        0x09 => 'Class',
        0x0A => 'CollectionId',
        0x0B => 'DateTime',
        0x0C => 'Estimate',
        0x0D => 'Response',
        0x0E => 'Status',
    },

    # FolderHierarchy
    0x07 => {
        0x07 => 'DisplayName',
        0x08 => 'ServerId',
        0x09 => 'ParentId',
        0x0A => 'Type',
        0x0C => 'Status',
        0x0E => 'Changes',
        0x0F => 'Add',
        0x10 => 'Delete',
        0x11 => 'Update',
        0x12 => 'SyncKey',
        0x13 => 'FolderCreate',
        0x14 => 'FolderDelete',
        0x15 => 'FolderUpdate',
        0x16 => 'FolderSync',
        0x17 => 'Count',
    },

    # MeetingResponse
    0x09 => {
        0x05 => 'CalendarId',
        0x06 => 'CollectionId',
        0x07 => 'MeetingResponse',
        0x08 => 'RequestId',
        0x09 => 'Request',
        0x0A => 'Result',
        0x0B => 'Status',
        0x0C => 'UserResponse',
        0x0E => 'InstanceId',
    },

    # ResolveRecipients
    0x0a => {
        0x05 => 'ResolveRecipients',
        0x06 => 'Response',
        0x07 => 'Status',
        0x08 => 'Type',
        0x09 => 'Recipient',
        0x0A => 'DisplayName',
        0x0B => 'EmailAddress',
        0x0C => 'Certificates',
        0x0D => 'Certificate',
        0x0E => 'MiniCertificate',
        0x0F => 'Options',
        0x10 => 'To',
        0x11 => 'CertificateRetrieval',
        0x12 => 'RecipientCount',
        0x13 => 'MaxCertificates',
        0x14 => 'MaxAmbiguousRecipients',
        0x15 => 'CertificateCount',
        0x16 => 'Availability',
        0x17 => 'StartTime',
        0x18 => 'EndTime',
        0x19 => 'MergedFreeBusy',
        0x1A => 'Picture',
        0x1B => 'MaxSize',
        0x1C => 'Data',
        0x1D => 'MaxPictures',
    },

    # ValidateCert
    0x0b => {
        0x05 => 'ValidateCert',
        0x06 => 'Certificates',
        0x07 => 'Certificate',
        0x08 => 'CertificateChain',
        0x09 => 'CheckCRL',
        0x0A => 'Status',
    },

    # Contacts2
    0x0c => {
        0x05 => 'CustomerId',
        0x06 => 'GovernmentId',
        0x07 => 'IMAddress',
        0x08 => 'IMAddress2',
        0x09 => 'IMAddress3',
        0x0A => 'ManagerName',
        0x0B => 'CompanyMainPhone',
        0x0C => 'AccountName',
        0x0D => 'NickName',
        0x0E => 'MMS',
    },

    # Ping
    0x0d => {
        0x05 => 'Ping',
        0x06 => 'AutdState',
        0x07 => 'Status',
        0x08 => 'HeartbeatInterval',
        0x09 => 'Folders',
        0x0A => 'Folder',
        0x0B => 'Id',
        0x0C => 'Class',
        0x0D => 'MaxFolders',
    },

    # Provision
    0x0e => {
        0x05 => 'Provision',
        0x06 => 'Policies',
        0x07 => 'Policy',
        0x08 => 'PolicyType',
        0x09 => 'PolicyKey',
        0x0A => 'Data',
        0x0B => 'Status',
        0x0C => 'RemoteWipe',
        0x0D => 'EASProvisionDoc',
        0x0E => 'DevicePasswordEnabled',
        0x0F => 'AlphanumericDevicePasswordRequired',
        0x10 => 'DeviceEncryptionEnabled',
        0x10 => 'RequireStorageCardEncryption',
        0x11 => 'PasswordRecoveryEnabled',
        0x13 => 'AttachmentsEnabled',
        0x14 => 'MinDevicePasswordLength',
        0x15 => 'MaxInactivityTimeDeviceLock',
        0x16 => 'MaxDevicePasswordFailedAttempts',
        0x17 => 'MaxAttachmentSize',
        0x18 => 'AllowSimpleDevicePassword',
        0x19 => 'DevicePasswordExpiration',
        0x1A => 'DevicePasswordHistory',
        0x1B => 'AllowStorageCard',
        0x1C => 'AllowCamera',
        0x1D => 'RequireDeviceEncryption',
        0x1E => 'AllowUnsignedApplications',
        0x1F => 'AllowUnsignedInstallationPackages',
        0x20 => 'MinDevicePasswordComplexCharacters',
        0x21 => 'AllowWiFi',
        0x22 => 'AllowTextMessaging',
        0x23 => 'AllowPOPIMAPEmail',
        0x24 => 'AllowBluetooth',
        0x25 => 'AllowIrDA',
        0x26 => 'RequireManualSyncWhenRoaming',
        0x27 => 'AllowDesktopSync',
        0x28 => 'MaxCalendarAgeFilter',
        0x29 => 'AllowHTMLEmail',
        0x2A => 'MaxEmailAgeFilter',
        0x2B => 'MaxEmailBodyTruncationSize',
        0x2C => 'MaxEmailHTMLBodyTruncationSize',
        0x2D => 'RequireSignedSMIMEMessages',
        0x2E => 'RequireEncryptedSMIMEMessages',
        0x2F => 'RequireSignedSMIMEAlgorithm',
        0x30 => 'RequireEncryptionSMIMEAlgorithm',
        0x31 => 'AllowSMIMEEncryptionAlgorithmNegotiation',
        0x32 => 'AllowSMIMESoftCerts',
        0x33 => 'AllowBrowser',
        0x34 => 'AllowConsumerEmail',
        0x35 => 'AllowRemoteDesktop',
        0x36 => 'AllowInternetSharing',
        0x37 => 'UnapprovedInROMApplicationList',
        0x38 => 'ApplicationName',
        0x39 => 'ApprovedApplicationList',
        0x3A => 'Hash',
    },

    # Search
    0x0f => {
        0x05 => 'Search',
        0x07 => 'Store',
        0x08 => 'Name',
        0x09 => 'Query',
        0x0A => 'Options',
        0x0B => 'Range',
        0x0C => 'Status',
        0x0D => 'Response',
        0x0E => 'Result',
        0x0F => 'Properties',
        0x10 => 'Total',
        0x11 => 'EqualTo',
        0x12 => 'Value',
        0x13 => 'And',
        0x14 => 'Or',
        0x15 => 'FreeText',
        0x17 => 'DeepTraversal',
        0x18 => 'LongId',
        0x19 => 'RebuildResults',
        0x1A => 'LessThan',
        0x1B => 'GreaterThan',
        0x1E => 'UserName',
        0x1F => 'Password',
        0x20 => 'ConversationId',
        0x21 => 'Picture',
        0x22 => 'MaxSize',
        0x23 => 'MaxPictures',
    },

    # GAL
    0x10 => {
        0x05 => 'DisplayName',
        0x06 => 'Phone',
        0x07 => 'Office',
        0x08 => 'Title',
        0x09 => 'Company',
        0x0A => 'Alias',
        0x0B => 'FirstName',
        0x0C => 'LastName',
        0x0D => 'HomePhone',
        0x0E => 'MobilePhone',
        0x0F => 'EmailAddress',
        0x10 => 'Picture',
        0x11 => 'Status',
        0x12 => 'Data',
    },

    # AirSyncBase
    0x11 => {
        0x05 => 'BodyPreference',
        0x06 => 'Type',
        0x07 => 'TruncationSize',
        0x08 => 'AllOrNone',
        0x0A => 'Body',
        0x0B => 'Data',
        0x0C => 'EstimatedDataSize',
        0x0D => 'Truncated',
        0x0E => 'Attachments',
        0x0F => 'Attachment',
        0x10 => 'DisplayName',
        0x11 => 'FileReference',
        0x12 => 'Method',
        0x13 => 'ContentId',
        0x14 => 'ContentLocation',
        0x15 => 'IsInline',
        0x16 => 'NativeBodyType',
        0x17 => 'ContentType',
        0x18 => 'Preview',
        0x19 => 'BodyPartPreference',
        0x1A => 'BodyPart',
        0x1B => 'Status',
    },

    # Settings
    0x12 => {
        0x05 => 'Settings',
        0x06 => 'Status',
        0x07 => 'Get',
        0x08 => 'Set',
        0x09 => 'Oof',
        0x0A => 'OofState',
        0x0B => 'StartTime',
        0x0C => 'EndTime',
        0x0D => 'OofMessage',
        0x0E => 'AppliesToInternal',
        0x0F => 'AppliesToExternalKnown',
        0x10 => 'AppliesToExternalUnknown',
        0x11 => 'Enabled',
        0x12 => 'ReplyMessage',
        0x13 => 'BodyType',
        0x14 => 'DevicePassword',
        0x15 => 'Password',
        0x16 => 'DeviceInformaton',
        0x17 => 'Model',
        0x18 => 'IMEI',
        0x19 => 'FriendlyName',
        0x1A => 'OS',
        0x1B => 'OSLanguage',
        0x1C => 'PhoneNumber',
        0x1D => 'UserInformation',
        0x1E => 'EmailAddresses',
        0x1F => 'SmtpAddress',
        0x20 => 'UserAgent',
        0x21 => 'EnableOutboundSMS',
        0x22 => 'MobileOperator',
        0x23 => 'PrimarySmtpAddress',
        0x24 => 'Accounts',
        0x25 => 'Account',
        0x26 => 'AccountId',
        0x27 => 'AccountName',
        0x28 => 'UserDisplayName',
        0x29 => 'SendDisabled',
        0x2B => 'ihsManagementInformation',
    },

    # DocumentLibrary
    0x13 => {
        0x05 => 'LinkId',
        0x06 => 'DisplayName',
        0x07 => 'IsFolder',
        0x08 => 'CreationDate',
        0x09 => 'LastModifiedDate',
        0x0A => 'IsHidden',
        0x0B => 'ContentLength',
        0x0C => 'ContentType',
    },

    # ItemOperations
    0x14 => {
        0x05 => 'ItemOperations',
        0x06 => 'Fetch',
        0x07 => 'Store',
        0x08 => 'Options',
        0x09 => 'Range',
        0x0A => 'Total',
        0x0B => 'Properties',
        0x0C => 'Data',
        0x0D => 'Status',
        0x0E => 'Response',
        0x0F => 'Version',
        0x10 => 'Schema',
        0x11 => 'Part',
        0x12 => 'EmptyFolderContents',
        0x13 => 'DeleteSubFolders',
        0x14 => 'UserName',
        0x15 => 'Password',
        0x16 => 'Move',
        0x17 => 'DstFldId',
        0x18 => 'ConversationId',
        0x19 => 'MoveAlways',
    },

    # ComposeMail
    0x15 => {
        0x05 => 'SendMail',
        0x06 => 'SmartForward',
        0x07 => 'SmartReply',
        0x08 => 'SaveInSentItems',
        0x09 => 'ReplaceMime',
        0x0B => 'Source',
        0x0C => 'FolderId',
        0x0D => 'ItemId',
        0x0E => 'LongId',
        0x0F => 'InstanceId',
        0x10 => 'MIME',
        0x11 => 'ClientId',
        0x12 => 'Status',
        0x13 => 'AccountId',
    },

    # Email2
    0x16 => {
        0x05 => 'UmCallerID',
        0x06 => 'UmUserNotes',
        0x07 => 'UmAttDuration',
        0x08 => 'UmAttOrder',
        0x09 => 'ConversationId',
        0x0A => 'ConversationIndex',
        0x0B => 'LastVerbExecuted',
        0x0C => 'LastVerbExecutionTime',
        0x0D => 'ReceivedAsBcc',
        0x0E => 'Sender',
        0x0F => 'CalendarType',
        0x10 => 'IsLeapMonth',
        0x11 => 'AccountId',
        0x12 => 'FirstDayOfWeek',
        0x13 => 'MeetingMessageType',
    },

    # Notes
    0x17 => {
        0x05 => 'Subject',
        0x06 => 'MessageClass',
        0x07 => 'LastModifiedDate',
        0x08 => 'Categories',
        0x09 => 'Category',
    },

    # RightsManagement
    0x18 => {
        0x05 => 'RightsManagementSupport',
        0x06 => 'RightsManagementTemplates',
        0x07 => 'RightsManagementTemplate',
        0x08 => 'RightsManagementLicense',
        0x09 => 'EditAllowed',
        0x0A => 'ReplyAllowed',
        0x0B => 'ReplyAllAllowed',
        0x0C => 'ForwardAllowed',
        0x0D => 'ModifyRecipientsAllowed',
        0x0E => 'ExtractAllowed',
        0x0F => 'PrintAllowed',
        0x10 => 'ExportAllowed',
        0x11 => 'ProgrammaticAccessAllowed',
        0x12 => 'RMOwner',
        0x13 => 'ContentExpiryDate',
        0x14 => 'TemplateID',
        0x15 => 'TemplateName',
        0x16 => 'TemplateDescription',
        0x17 => 'ContentOwner',
        0x18 => 'RemoveRightsManagementDistribution',
    }
};

our $TAGS = {

    # 0x00
    AirSync => {
        'Sync'              => 0x05,
        'Responses'         => 0x06,
        'Add'               => 0x07,
        'Change'            => 0x08,
        'Delete'            => 0x09,
        'Fetch'             => 0x0A,
        'SyncKey'           => 0x0B,
        'ClientId'          => 0x0C,
        'ServerId'          => 0x0D,
        'Status'            => 0x0E,
        'Collection'        => 0x0F,
        'Class'             => 0x10,
        'CollectionId'      => 0x12,
        'GetChanges'        => 0x13,
        'MoreAvailable'     => 0x14,
        'WindowSize'        => 0x15,
        'Commands'          => 0x16,
        'Options'           => 0x17,
        'FilterType'        => 0x18,
        'Conflict'          => 0x1B,
        'Collections'       => 0x1C,
        'ApplicationData'   => 0x1D,
        'DeletesAsMoves'    => 0x1E,
        'Supported'         => 0x20,
        'SoftDelete'        => 0x21,
        'MIMESupport'       => 0x22,
        'MIMETruncation'    => 0x23,
        'Wait'              => 0x24,
        'Limit'             => 0x25,
        'Partial'           => 0x26,
        'ConversationMode'  => 0x27,
        'MaxItems'          => 0x28,
        'HeartbeatInterval' => 0x29,
    },

    # 0x01
    Contacts => {
        'Anniversary'              => 0x05,
        'AssistantName'            => 0x06,
        'AssistantTelephoneNumber' => 0x07,
        'Birthday'                 => 0x08,
        'Business2PhoneNumber'     => 0x0C,
        'BusinessCity'             => 0x0D,
        'BusinessCountry'          => 0x0E,
        'BusinessPostalCode'       => 0x0F,
        'BusinessState'            => 0x10,
        'BusinessStreet'           => 0x11,
        'BusinessFaxNumber'        => 0x12,
        'BusinessPhoneNumber'      => 0x13,
        'CarPhoneNumber'           => 0x14,
        'Categories'               => 0x15,
        'Category'                 => 0x16,
        'Children'                 => 0x17,
        'Child'                    => 0x18,
        'CompanyName'              => 0x19,
        'Department'               => 0x1A,
        'Email1Address'            => 0x1B,
        'Email2Address'            => 0x1C,
        'Email3Address'            => 0x1D,
        'FileAs'                   => 0x1E,
        'FirstName'                => 0x1F,
        'Home2PhoneNumber'         => 0x20,
        'HomeCity'                 => 0x21,
        'HomeCountry'              => 0x22,
        'HomePostalCode'           => 0x23,
        'HomeState'                => 0x24,
        'HomeStreet'               => 0x25,
        'HomeFaxNumber'            => 0x26,
        'HomePhoneNumber'          => 0x27,
        'JobTitle'                 => 0x28,
        'LastName'                 => 0x29,
        'MiddleName'               => 0x2A,
        'MobilePhoneNumber'        => 0x2B,
        'OfficeLocation'           => 0x2C,
        'OtherCity'                => 0x2D,
        'OtherCountry'             => 0x2E,
        'OtherPostalCode'          => 0x2F,
        'OtherState'               => 0x30,
        'OtherStreet'              => 0x31,
        'PagerNumber'              => 0x32,
        'RadioPhoneNumber'         => 0x33,
        'Spouse'                   => 0x34,
        'Suffix'                   => 0x35,
        'Title'                    => 0x36,
        'Webpage'                  => 0x37,
        'YomiCompanyName'          => 0x38,
        'YomiFirstName'            => 0x39,
        'YomiLastName'             => 0x3A,
        'Picture'                  => 0x3C,
        'Alias'                    => 0x3D,
        'WeightedRank'             => 0x3E,
    },

    # 0x02
    Email => {
        'DateReceived'            => 0x0F,
        'DisplayTo'               => 0x11,
        'Importance'              => 0x12,
        'MessageClass'            => 0x13,
        'Subject'                 => 0x14,
        'Read'                    => 0x15,
        'To'                      => 0x16,
        'CC'                      => 0x17,
        'From'                    => 0x18,
        'ReplyTo'                 => 0x19,
        'AllDayEvent'             => 0x1A,
        'Categories'              => 0x1B,
        'Category'                => 0x1C,
        'DTStamp'                 => 0x1D,
        'EndTime'                 => 0x1E,
        'InstanceType'            => 0x1F,
        'BusyStatus'              => 0x20,
        'Location'                => 0x21,
        'MeetingRequest'          => 0x22,
        'Organizer'               => 0x23,
        'RecurrenceId'            => 0x24,
        'Reminder'                => 0x25,
        'ResponseRequested'       => 0x26,
        'Recurrences'             => 0x27,
        'Recurrence'              => 0x28,
        'Recurrence_Type'         => 0x29,
        'Recurrence_Until'        => 0x2A,
        'Recurrence_Occurrences'  => 0x2B,
        'Recurrence_Interval'     => 0x2C,
        'Recurrence_DayOfWeek'    => 0x2D,
        'Recurrence_DayOfMonth'   => 0x2E,
        'Recurrence_WeekOfMonth'  => 0x2F,
        'Recurrence_MonthOfYear'  => 0x30,
        'StartTime'               => 0x31,
        'Sensitivity'             => 0x32,
        'TimeZone'                => 0x33,
        'GlobalObjId'             => 0x34,
        'ThreadTopic'             => 0x35,
        'InternetCPID'            => 0x39,
        'Flag'                    => 0x3A,
        'FlagStatus'              => 0x3B,
        'ContentClass'            => 0x3C,
        'FlagType'                => 0x3D,
        'CompleteTime'            => 0x3E,
        'DisallowNewTimeProposal' => 0x3F,
    },

    # 0x04
    Calendar => {
        'TimeZone'                  => 0x05,
        'AllDayEvent'               => 0x06,
        'Attendees'                 => 0x07,
        'Attendee'                  => 0x08,
        'Attendee_Email'            => 0x09,
        'Attendee_Name'             => 0x0A,
        'BusyStatus'                => 0x0D,
        'Categories'                => 0x0E,
        'Category'                  => 0x0F,
        'DTStamp'                   => 0x11,
        'EndTime'                   => 0x12,
        'Exception'                 => 0x13,
        'Exceptions'                => 0x14,
        'Exception_Deleted'         => 0x15,
        'Exception_StartTime'       => 0x16,
        'Location'                  => 0x17,
        'MeetingStatus'             => 0x18,
        'Organizer_Email'           => 0x19,
        'Organizer_Name'            => 0x1A,
        'Recurrence'                => 0x1B,
        'Recurrence_Type'           => 0x1C,
        'Recurrence_Until'          => 0x1D,
        'Recurrence_Occurrences'    => 0x1E,
        'Recurrence_Interval'       => 0x1F,
        'Recurrence_DayOfWeek'      => 0x20,
        'Recurrence_DayOfMonth'     => 0x21,
        'Recurrence_WeekOfMonth'    => 0x22,
        'Recurrence_MonthOfYear'    => 0x23,
        'Reminder'                  => 0x24,
        'Sensitivity'               => 0x25,
        'Subject'                   => 0x26,
        'StartTime'                 => 0x27,
        'UID'                       => 0x28,
        'Attendee_Status'           => 0x29,
        'Attendee_Type'             => 0x2A,
        'DisallowNewTimeProposal'   => 0x33,
        'ResponseRequested'         => 0x34,
        'AppointmentReplyTime'      => 0x35,
        'ResponseType'              => 0x36,
        'CalendarType'              => 0x37,
        'IsLeapMonth'               => 0x38,
        'FirstDayOfWeek'            => 0x39,
        'OnlineMeetingConfLink'     => 0x3A,
        'OnlineMeetingExternalLink' => 0x3B,
    },

    # 0x05
    Move => {
        'MoveItems' => 0x05,
        'Move'      => 0x06,
        'SrcMsgId'  => 0x07,
        'SrcFldId'  => 0x08,
        'DstFldId'  => 0x09,
        'Response'  => 0x0A,
        'Status'    => 0x0B,
        'DstMsgId'  => 0x0C,
    },

    # 0x06
    ItemEstimate => {
        'GetItemEstimate' => 0x05,
        'Version'         => 0x06,
        'Collections'     => 0x07,
        'Collection'      => 0x08,
        'Class'           => 0x09,
        'CollectionId'    => 0x0A,
        'DateTime'        => 0x0B,
        'Estimate'        => 0x0C,
        'Response'        => 0x0D,
        'Status'          => 0x0E,
    },

    # 0x07
    FolderHierarchy => {
        'DisplayName'  => 0x07,
        'ServerId'     => 0x08,
        'ParentId'     => 0x09,
        'Type'         => 0x0A,
        'Status'       => 0x0C,
        'Changes'      => 0x0E,
        'Add'          => 0x0F,
        'Delete'       => 0x10,
        'Update'       => 0x11,
        'SyncKey'      => 0x12,
        'FolderCreate' => 0x13,
        'FolderDelete' => 0x14,
        'FolderUpdate' => 0x15,
        'FolderSync'   => 0x16,
        'Count'        => 0x17,
    },

    # 0x09
    MeetingResponse => {
        'CalendarId'      => 0x05,
        'CollectionId'    => 0x06,
        'MeetingResponse' => 0x07,
        'RequestId'       => 0x08,
        'Request'         => 0x09,
        'Result'          => 0x0A,
        'Status'          => 0x0B,
        'UserResponse'    => 0x0C,
        'InstanceId'      => 0x0E,
    },

    # 0x0a
    ResolveRecipients => {
        'ResolveRecipients'      => 0x05,
        'Response'               => 0x06,
        'Status'                 => 0x07,
        'Type'                   => 0x08,
        'Recipient'              => 0x09,
        'DisplayName'            => 0x0A,
        'EmailAddress'           => 0x0B,
        'Certificates'           => 0x0C,
        'Certificate'            => 0x0D,
        'MiniCertificate'        => 0x0E,
        'Options'                => 0x0F,
        'To'                     => 0x10,
        'CertificateRetrieval'   => 0x11,
        'RecipientCount'         => 0x12,
        'MaxCertificates'        => 0x13,
        'MaxAmbiguousRecipients' => 0x14,
        'CertificateCount'       => 0x15,
        'Availability'           => 0x16,
        'StartTime'              => 0x17,
        'EndTime'                => 0x18,
        'MergedFreeBusy'         => 0x19,
        'Picture'                => 0x1A,
        'MaxSize'                => 0x1B,
        'Data'                   => 0x1C,
        'MaxPictures'            => 0x1D,
    },

    # 0x0b
    ValidateCert => {
        'ValidateCert'     => 0x05,
        'Certificates'     => 0x06,
        'Certificate'      => 0x07,
        'CertificateChain' => 0x08,
        'CheckCRL'         => 0x09,
        'Status'           => 0x0A,
    },

    # 0x0c
    Contacts2 => {
        'CustomerId'       => 0x05,
        'GovernmentId'     => 0x06,
        'IMAddress'        => 0x07,
        'IMAddress2'       => 0x08,
        'IMAddress3'       => 0x09,
        'ManagerName'      => 0x0A,
        'CompanyMainPhone' => 0x0B,
        'AccountName'      => 0x0C,
        'NickName'         => 0x0D,
        'MMS'              => 0x0E,
    },

    # 0x0d
    Ping => {
        'Ping'              => 0x05,
        'AutdState'         => 0x06,
        'Status'            => 0x07,
        'HeartbeatInterval' => 0x08,
        'Folders'           => 0x09,
        'Folder'            => 0x0A,
        'Id'                => 0x0B,
        'Class'             => 0x0C,
        'MaxFolders'        => 0x0D,
    },

    # 0x0e
    Provision => {
        'Provision'                                => 0x05,
        'Policies'                                 => 0x06,
        'Policy'                                   => 0x07,
        'PolicyType'                               => 0x08,
        'PolicyKey'                                => 0x09,
        'Data'                                     => 0x0A,
        'Status'                                   => 0x0B,
        'RemoteWipe'                               => 0x0C,
        'EASProvisionDoc'                          => 0x0D,
        'DevicePasswordEnabled'                    => 0x0E,
        'AlphanumericDevicePasswordRequired'       => 0x0F,
        'DeviceEncryptionEnabled'                  => 0x10,
        'RequireStorageCardEncryption'             => 0x10,
        'PasswordRecoveryEnabled'                  => 0x11,
        'AttachmentsEnabled'                       => 0x13,
        'MinDevicePasswordLength'                  => 0x14,
        'MaxInactivityTimeDeviceLock'              => 0x15,
        'MaxDevicePasswordFailedAttempts'          => 0x16,
        'MaxAttachmentSize'                        => 0x17,
        'AllowSimpleDevicePassword'                => 0x18,
        'DevicePasswordExpiration'                 => 0x19,
        'DevicePasswordHistory'                    => 0x1A,
        'AllowStorageCard'                         => 0x1B,
        'AllowCamera'                              => 0x1C,
        'RequireDeviceEncryption'                  => 0x1D,
        'AllowUnsignedApplications'                => 0x1E,
        'AllowUnsignedInstallationPackages'        => 0x1F,
        'MinDevicePasswordComplexCharacters'       => 0x20,
        'AllowWiFi'                                => 0x21,
        'AllowTextMessaging'                       => 0x22,
        'AllowPOPIMAPEmail'                        => 0x23,
        'AllowBluetooth'                           => 0x24,
        'AllowIrDA'                                => 0x25,
        'RequireManualSyncWhenRoaming'             => 0x26,
        'AllowDesktopSync'                         => 0x27,
        'MaxCalendarAgeFilter'                     => 0x28,
        'AllowHTMLEmail'                           => 0x29,
        'MaxEmailAgeFilter'                        => 0x2A,
        'MaxEmailBodyTruncationSize'               => 0x2B,
        'MaxEmailHTMLBodyTruncationSize'           => 0x2C,
        'RequireSignedSMIMEMessages'               => 0x2D,
        'RequireEncryptedSMIMEMessages'            => 0x2E,
        'RequireSignedSMIMEAlgorithm'              => 0x2F,
        'RequireEncryptionSMIMEAlgorithm'          => 0x30,
        'AllowSMIMEEncryptionAlgorithmNegotiation' => 0x31,
        'AllowSMIMESoftCerts'                      => 0x32,
        'AllowBrowser'                             => 0x33,
        'AllowConsumerEmail'                       => 0x34,
        'AllowRemoteDesktop'                       => 0x35,
        'AllowInternetSharing'                     => 0x36,
        'UnapprovedInROMApplicationList'           => 0x37,
        'ApplicationName'                          => 0x38,
        'ApprovedApplicationList'                  => 0x39,
        'Hash'                                     => 0x3A,
    },

    # 0x0f
    Search => {
        'Search'         => 0x05,
        'Store'          => 0x07,
        'Name'           => 0x08,
        'Query'          => 0x09,
        'Options'        => 0x0A,
        'Range'          => 0x0B,
        'Status'         => 0x0C,
        'Response'       => 0x0D,
        'Result'         => 0x0E,
        'Properties'     => 0x0F,
        'Total'          => 0x10,
        'EqualTo'        => 0x11,
        'Value'          => 0x12,
        'And'            => 0x13,
        'Or'             => 0x14,
        'FreeText'       => 0x15,
        'DeepTraversal'  => 0x17,
        'LongId'         => 0x18,
        'RebuildResults' => 0x19,
        'LessThan'       => 0x1A,
        'GreaterThan'    => 0x1B,
        'UserName'       => 0x1E,
        'Password'       => 0x1F,
        'ConversationId' => 0x20,
        'Picture'        => 0x21,
        'MaxSize'        => 0x22,
        'MaxPictures'    => 0x23,
    },

    # 0x10
    GAL => {
        'DisplayName'  => 0x05,
        'Phone'        => 0x06,
        'Office'       => 0x07,
        'Title'        => 0x08,
        'Company'      => 0x09,
        'Alias'        => 0x0A,
        'FirstName'    => 0x0B,
        'LastName'     => 0x0C,
        'HomePhone'    => 0x0D,
        'MobilePhone'  => 0x0E,
        'EmailAddress' => 0x0F,
        'Picture'      => 0x10,
        'Status'       => 0x11,
        'Data'         => 0x12,
    },

    # 0x11
    AirSyncBase => {
        'BodyPreference'     => 0x05,
        'Type'               => 0x06,
        'TruncationSize'     => 0x07,
        'AllOrNone'          => 0x08,
        'Body'               => 0x0A,
        'Data'               => 0x0B,
        'EstimatedDataSize'  => 0x0C,
        'Truncated'          => 0x0D,
        'Attachments'        => 0x0E,
        'Attachment'         => 0x0F,
        'DisplayName'        => 0x10,
        'FileReference'      => 0x11,
        'Method'             => 0x12,
        'ContentId'          => 0x13,
        'ContentLocation'    => 0x14,
        'IsInline'           => 0x15,
        'NativeBodyType'     => 0x16,
        'ContentType'        => 0x17,
        'Preview'            => 0x18,
        'BodyPartPreference' => 0x19,
        'BodyPart'           => 0x1A,
        'Status'             => 0x1B,
    },

    # 0x12
    Settings => {
        'Settings'                 => 0x05,
        'Status'                   => 0x06,
        'Get'                      => 0x07,
        'Set'                      => 0x08,
        'Oof'                      => 0x09,
        'OofState'                 => 0x0A,
        'StartTime'                => 0x0B,
        'EndTime'                  => 0x0C,
        'OofMessage'               => 0x0D,
        'AppliesToInternal'        => 0x0E,
        'AppliesToExternalKnown'   => 0x0F,
        'AppliesToExternalUnknown' => 0x10,
        'Enabled'                  => 0x11,
        'ReplyMessage'             => 0x12,
        'BodyType'                 => 0x13,
        'DevicePassword'           => 0x14,
        'Password'                 => 0x15,
        'DeviceInformaton'         => 0x16,
        'Model'                    => 0x17,
        'IMEI'                     => 0x18,
        'FriendlyName'             => 0x19,
        'OS'                       => 0x1A,
        'OSLanguage'               => 0x1B,
        'PhoneNumber'              => 0x1C,
        'UserInformation'          => 0x1D,
        'EmailAddresses'           => 0x1E,
        'SmtpAddress'              => 0x1F,
        'UserAgent'                => 0x20,
        'EnableOutboundSMS'        => 0x21,
        'MobileOperator'           => 0x22,
        'PrimarySmtpAddress'       => 0x23,
        'Accounts'                 => 0x24,
        'Account'                  => 0x25,
        'AccountId'                => 0x26,
        'AccountName'              => 0x27,
        'UserDisplayName'          => 0x28,
        'SendDisabled'             => 0x29,
        'ihsManagementInformation' => 0x2B,
    },

    # 0x13
    DocumentLibrary => {
        'LinkId'           => 0x05,
        'DisplayName'      => 0x06,
        'IsFolder'         => 0x07,
        'CreationDate'     => 0x08,
        'LastModifiedDate' => 0x09,
        'IsHidden'         => 0x0A,
        'ContentLength'    => 0x0B,
        'ContentType'      => 0x0C,
    },

    # 0x14
    ItemOperations => {
        'ItemOperations'      => 0x05,
        'Fetch'               => 0x06,
        'Store'               => 0x07,
        'Options'             => 0x08,
        'Range'               => 0x09,
        'Total'               => 0x0A,
        'Properties'          => 0x0B,
        'Data'                => 0x0C,
        'Status'              => 0x0D,
        'Response'            => 0x0E,
        'Version'             => 0x0F,
        'Schema'              => 0x10,
        'Part'                => 0x11,
        'EmptyFolderContents' => 0x12,
        'DeleteSubFolders'    => 0x13,
        'UserName'            => 0x14,
        'Password'            => 0x15,
        'Move'                => 0x16,
        'DstFldId'            => 0x17,
        'ConversationId'      => 0x18,
        'MoveAlways'          => 0x19,
    },

    # 0x15
    ComposeMail => {
        'SendMail'        => 0x05,
        'SmartForward'    => 0x06,
        'SmartReply'      => 0x07,
        'SaveInSentItems' => 0x08,
        'ReplaceMime'     => 0x09,
        'Source'          => 0x0B,
        'FolderId'        => 0x0C,
        'ItemId'          => 0x0D,
        'LongId'          => 0x0E,
        'InstanceId'      => 0x0F,
        'MIME'            => 0x10,
        'ClientId'        => 0x11,
        'Status'          => 0x12,
        'AccountId'       => 0x13,
    },

    # 0x16
    Email2 => {
        'UmCallerID'            => 0x05,
        'UmUserNotes'           => 0x06,
        'UmAttDuration'         => 0x07,
        'UmAttOrder'            => 0x08,
        'ConversationId'        => 0x09,
        'ConversationIndex'     => 0x0A,
        'LastVerbExecuted'      => 0x0B,
        'LastVerbExecutionTime' => 0x0C,
        'ReceivedAsBcc'         => 0x0D,
        'Sender'                => 0x0E,
        'CalendarType'          => 0x0F,
        'IsLeapMonth'           => 0x10,
        'AccountId'             => 0x11,
        'FirstDayOfWeek'        => 0x12,
        'MeetingMessageType'    => 0x13,
    },

    # 0x17
    Notes => {
        'Subject'          => 0x05,
        'MessageClass'     => 0x06,
        'LastModifiedDate' => 0x07,
        'Categories'       => 0x08,
        'Category'         => 0x09,
    },

    # 0x18
    RightsManagement => {
        'RightsManagementSupport'            => 0x05,
        'RightsManagementTemplates'          => 0x06,
        'RightsManagementTemplate'           => 0x07,
        'RightsManagementLicense'            => 0x08,
        'EditAllowed'                        => 0x09,
        'ReplyAllowed'                       => 0x0A,
        'ReplyAllAllowed'                    => 0x0B,
        'ForwardAllowed'                     => 0x0C,
        'ModifyRecipientsAllowed'            => 0x0D,
        'ExtractAllowed'                     => 0x0E,
        'PrintAllowed'                       => 0x0F,
        'ExportAllowed'                      => 0x10,
        'ProgrammaticAccessAllowed'          => 0x11,
        'RMOwner'                            => 0x12,
        'ContentExpiryDate'                  => 0x13,
        'TemplateID'                         => 0x14,
        'TemplateName'                       => 0x15,
        'TemplateDescription'                => 0x16,
        'ContentOwner'                       => 0x17,
        'RemoveRightsManagementDistribution' => 0x18,
    }
};

1;
